FROM node:20-alpine

WORKDIR /app

COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install

COPY ./frontend/ ./

RUN npm run build

RUN npm install -g http-server

EXPOSE 8081

CMD ["http-server", ".", "-p", "8081", "-a", "0.0.0.0"]
